<a href="https://colab.research.google.com/github/euan-nr/Project-SCORE/blob/main/Project_SCORE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Project SCORE**


> **S**tatistical **C**haracter **O**ptical **R**ecognition **E**xercise

This notebook seeks to use OCR library Pytesseract to read screenshots from the mobile game Score Match, created by First Touch Games

The end goal is for statistical analysis to be performed on the data obtained for a player's own entertainment

All Score Match player descriptions and naming rights belong to First Touch Games.

In [ ]:
import cv2
!pip install pytesseract
import pytesseract
from PIL import Image
!sudo apt install tesseract-ocr
pytesseract.pytesseract.tesseract_cmd = r'/usr/bin/tesseract'

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pytesseract in /usr/local/lib/python3.10/dist-packages (0.3.10)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.10/dist-packages (from pytesseract) (23.1)
Requirement already satisfied: Pillow>=8.0.0 in /usr/local/lib/python3.10/dist-packages (from pytesseract) (8.4.0)
Reading package lists... Done
Building dependency tree
Reading state information... Done
tesseract-ocr is already the newest version (4.1.1-2build2).
0 upgraded, 0 newly installed, 0 to remove and 24 not upgraded.

In [ ]:
#Test block
img=r'/content/screenshot1.jpg'
text = pytesseract.image_to_string(Image.open(img))
print(text)

In [ ]:
#using openCV (not as accurate)
img=cv2.imread(r'/content/screenshot1.jpg')
text=pytesseract.image_to_string(img)
print(text)

In [ ]:
import pandas as pd
import re
import os, glob
from pathlib import WindowsPath
import locale
locale.setlocale(locale.LC_ALL, 'en_US.UTF-8')
#to convert strings with commas to floats

'en_US.UTF-8'

In [ ]:
#Test block
#Read all text in folder
folder= "/content/drive/MyDrive/ProjectSCORE"
files=glob.glob(folder+".jpg")
f=[]
t=[]
for root,_,file in os.walk(folder):
    for filename in file:
        f.append(filename)
        img1 = Image.open(folder+'/'+ filename)
        text = pytesseract.image_to_string(img1, lang = 'eng')
        t.append(text)
        print(text)
        #print('-='*20)

MARTINA STATISTICS

(QLLSCLUMER 4 speed

Height
Strength
Power
Skill
Response

Played: 1,219 Won: 719 Lost: 500 Scored: 24

Lends a hand all over the pitch, but always with style,
erate UC eee te

MAGICIAN BEHAVIOUR
_RASSINGs

Attacking

oy

Pass Dribble Clear Marking Running



STATISTICS

& Speed

ft Height

G Strength
“\ Power

©) Skill

*@ Response

Played: 630 Won: 407 Lost: 223 Scored: 5

Confidence is assured with this player - a real leader.

HERO BEHAVIOUR
_PASSINGs

Attacking

oe vx

Pass Dribble Clear Marking Running





STATISTICS
Speed
Height
Strength
Power
Skill
Response

Played: 2,840 Won: 1,708 Lost: 1,132 Scored: 13

A natural ball winner. Thinks before playing the ball out
of danger.

PROTECTOR BEHAVIOUR
=

Attacking

S “x

Shoot Pass Dribble Clear Marking Running



STATISTICS
Speed
Height
Strength
Power
Skill
@ Response

Played: 2,354 Won: 1,479 Lost: 875 Scored: 10

An uncompromising ball winner, with an eye upfield,
turning defence into attack.

RAIDER BEHAVIOUR

Attacking
S vw vv

Shoot Pass Dribble Clear Marking Running



ft Height
G Strength
% Power

Played: 5,083 Won: 2,844 Lost: 2,239 Scored: 103

TU CU] tackles, cool control, and
punishing speed!

INVADER BEHAVIOUR
— 1

Attacking
C hd wy
Running

Pass Dribble Clear Marking





PATRIZIO STATISTICS

(OLAZEa 4 seeea

Height
Strength
9 4 ' Power
Skill
Response

Played: 5,615 Won: 3,167 Lost: 2,448 Scored: 29

With his vast array of abilities, this player can change the
Emm me CCl:

VOYAGER BEHAVIOUR

7 Safe ae

Pass Dribble Clear Marking Running





CERNAT STATISTICS

(QUAL 4 speed

Height
Strength
Power
Skill
Response

Played: 4,035 Won: 2,083 Lost: 1,952 Conceded: 3,912

PM Cl Tee CN Me lM Cele Cad eer Ui)
build and support from the back!

GK-SWEEPER BEHAVIOUR
Attacking
ee

VW

Pass Dribble Clear Marking Running



SANDBERG STATISTICS

(OL 4 speed

Height
Strength
Power
Skill

@ Response

Played: 4,565 Won: 2,720 Lost: 1,845 Scored: 817

Tee ati Cm OR CCR ed
POR CUR aU ee: Cry

POACHER BEHAVIOUR

Attacking

oY

Pass Dribble Clear Marking Running





EUANITO STATISTICS

GLUE 4 speed

Height
Strength
Power
Skill
Response

(Cy

Played: 12,398 Won: 6,727 Lost: 5,671 Scored: 2,897

Easy to find. Difficult to stop. Uses power to dominate his
opponent.

HAMMER BEHAVIOUR
—

Attacking

WV

Pass Dribble Clear Marking Running

CUSTOMISE
dN A





ZIVKOVIC STATISTICS

(+3) COMPOSER | Pm

Height
Strength
Power
Skill
Response

Played: 5,935 Won: 3,440 Lost: 2,495 Scored: 225

Slices open teams with acute passing from great distances
like a quarterback.

COMPOSER BEHAVIOUR
a

Attacking

J
te U

Shoot Pass Dribble Clear Marking Running



ABUBAKAR STATISTICS
Speed

Height
Strength
Power
Skill

@ Response

Played: 4,221 Won: 2,558 Lost: 1,663 Scored: 1,651

A cool head on broad shoulders, that can change games in
a flash with his pace.

LIGHTNING BEHAVIOUR

PASSING,

Attacking
ee Wy

Shoot Pass Dribble Clear Marking Running

In [ ]:
#read one file
player_name=str(text.split('STATISTICS')[0])
sub1="Played:"
sub2="Won:"
sub3="Lost:"
sub4="Scored:"
s1=str(re.escape(sub1))
s2=str(re.escape(sub2))
s3=str(re.escape(sub3))
s4=str(re.escape(sub4))
sub5="   "
s5=str(re.escape(sub5))
games_played=locale.atoi(re.findall(s1+"(.*)"+s2,text)[0])
wins=locale.atoi(re.findall(s2+"(.*)"+s3,text)[0])
losses=locale.atoi(re.findall(s3+"(.*)"+s4,text)[0])
goals_scored=locale.atoi(re.findall(s4+"(.*)",text)[0])
print("Player Name:",player_name)
print("Games Played:",games_played)
print("Wins:",wins)
print("Losses:",losses)
print("Goals Scored:",goals_scored)
_data=[player_name,games_played,wins,losses,goals_scored]

Player Name: ABUBAKAR
Games Played: 4221
Wins: 2558
Losses: 1663
Goals Scored: 1651

In [ ]:
folder= "/content/drive/MyDrive/ProjectSCORE"
files=glob.glob(folder+".jpg")
f=[]
t=[]
player_data=pd.DataFrame(columns=['name','position','games_played','wins','losses','goals_scored'])
for root,_,file in os.walk(folder):
    for filename in file:
        f.append(filename)
        img2 = Image.open(folder+'/'+ filename)
        text = pytesseract.image_to_string(img2, lang = 'eng')
        t.append(text)
        #print(text)
        player_name=str(text.split('STATISTICS')[0])
        player_name=re.sub('[^A-Z]', '', player_name)
        sub1="Played:"
        sub2="Won:"
        sub3="Lost:"
        if "Conceded:" in text:
          sub4="Conceded:"
        else:
          sub4="Scored:"
        sub5="BEHAVIOUR"
        s1=str(re.escape(sub1))
        s2=str(re.escape(sub2))
        s3=str(re.escape(sub3))
        s4=str(re.escape(sub4))
        s5=str(re.escape(sub5))
        if sub5 in text:
          position=re.findall(""+"(.*)"+s5,text)[0]
        else:
          position=None
        games_played=locale.atoi(re.findall(s1+"(.*)"+s2,text)[0])
        wins=locale.atoi(re.findall(s2+"(.*)"+s3,text)[0])
        losses=locale.atoi(re.findall(s3+"(.*)"+s4,text)[0])
        if "GK" in text:
          goals_scored=locale.atoi(re.findall(s4+"(.*)",text)[0])*-1
        else:
          goals_scored=locale.atoi(re.findall(s4+"(.*)",text)[0])
        _data=[player_name,position,games_played,wins,losses,goals_scored]
        player_data.loc[len(player_data)]=_data
        print("Player Name:",player_name)
        print("Position:",position)
        print("Games Played:",games_played)
        print("Wins:",wins)
        print("Losses:",losses)
        print("Goals Scored:",goals_scored)

Player Name: MARTINA
Position: MAGICIAN
Games Played: 1219
Wins: 719
Losses: 500
Goals Scored: 24
Player Name:
Position: HERO
Games Played: 630
Wins: 407
Losses: 223
Goals Scored: 5
Player Name:
Position: PROTECTOR
Games Played: 2840
Wins: 1708
Losses: 1132
Goals Scored: 13
Player Name:
Position: RAIDER
Games Played: 2354
Wins: 1479
Losses: 875
Goals Scored: 10
Player Name: HGSPPWLSTUCUINVADERBEHAVIOURACRPDCM
Position: INVADER
Games Played: 5083
Wins: 2844
Losses: 2239
Goals Scored: 103
Player Name: PATRIZIO
Position: VOYAGER
Games Played: 5615
Wins: 3167
Losses: 2448
Goals Scored: 29
Player Name: CERNAT
Position: GK-SWEEPER
Games Played: 4035
Wins: 2083
Losses: 1952
Goals Scored: -3912
Player Name: SANDBERG
Position: POACHER
Games Played: 4565
Wins: 2720
Losses: 1845
Goals Scored: 817
Player Name: EUANITO
Position: HAMMER
Games Played: 12398
Wins: 6727
Losses: 5671
Goals Scored: 2897
Player Name: ZIVKOVIC
Position: COMPOSER
Games Played: 5935
Wins: 3440
Losses: 2495
Goals Scored: 225
Player Name: ABUBAKAR
Position: LIGHTNING
Games Played: 4221
Wins: 2558
Losses: 1663
Goals Scored: 1651

In [ ]:
#Test Block
player_data=pd.DataFrame(columns=['name','games_played','wins','losses','goals_scored'])
player_data.loc[len(player_data)]=_data
player_data.dtypes

name            object
games_played     int64
wins             int64
losses           int64
goals_scored     int64
dtype: object

In [ ]:
player_data

,name,position,games_played,wins,losses,goals_scored
0,MARTINA,MAGICIAN,1219,719,500,24
1,,HERO,630,407,223,5
2,,PROTECTOR,2840,1708,1132,13
3,,RAIDER,2354,1479,875,10
4,HGSPPWLSTUCUINVADERBEHAVIOURACRPDCM,INVADER,5083,2844,2239,103
5,PATRIZIO,VOYAGER,5615,3167,2448,29
6,CERNAT,GK-SWEEPER,4035,2083,1952,-3912
7,SANDBERG,POACHER,4565,2720,1845,817
8,EUANITO,HAMMER,12398,6727,5671,2897
9,ZIVKOVIC,COMPOSER,5935,3440,2495,225
10,ABUBAKAR,LIGHTNING,4221,2558,1663,1651